// Generated by https://quicktype.io

export interface stripeUser {
  id:                    string;
  object:                string;
  address?:               Address;
  balance:               number;
  created:               number;
  currency:              string;
  default_source:        null;
  delinquent:            boolean;
  description:           string;
  discount:              null;
  email:                 string;
  invoice_prefix:        string;
  invoice_settings:      InvoiceSettings;
  livemode:              boolean;
  metadata:              Metadata;
  name:                  string;
  next_invoice_sequence: number;
  phone:                 string;
  preferred_locales:     any[];
  shipping:              null;
  tax_exempt:            string;
  test_clock:            null;
}

export interface Address {
  city:        string;
  country:     string;
  line1:       string;
  line2:       null;
  postal_code: string;
  state:       string;
}

export interface InvoiceSettings {
  custom_fields:          null;
  default_payment_method: null;
  footer:                 null;
  rendering_options:      null;
}

export interface Metadata {
}


export interface Users {
  id:         number;
  email:      string;
  first_name: string;
  last_name:  string;
  avatar:     string;
}

