[dev]
  targetPort = 3005
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "./functions"  
[[plugins]]
package = "@netlify/plugin-functions-install-core"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

